name: Docker CI with Trivy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build frontend image
      run: docker build -t frontend:latest ./frontend

    - name: Build backend image
      run: docker build -t backend:latest ./backend

    - name: Install Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: image
        image-ref: frontend:latest

    - name: Scan backend image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: image
        image-ref: backend:latest

